<a href="https://colab.research.google.com/github/henry921630/DataScience60Days/blob/main/DataScience60Days_day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
# 題目:
# english_score = np.array([55,89,76,65,48,70])
# math_score = np.array([60,85,60,68,np.nan,60])
# chinese_score = np.array([65,90,82,72,66,77])
# 上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

# 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
# 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
# 用補考後資料找出與國文成績相關係數最高的學科?

In [43]:
import numpy as np

In [44]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [45]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
all_subject_score = np.array([english_score, math_score, chinese_score])
print(
np.nanmean(all_subject_score, axis=1),
np.nanmax(all_subject_score, axis =1),
np.nanmin(all_subject_score, axis =1),
np.nanstd(all_subject_score, axis =1),
sep= '\n')

[67.16666667 66.6        75.33333333]
[89. 85. 90.]
[48. 60. 65.]
[13.43399502  9.70772888  8.8254682 ]


In [48]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
all_subject_score_after =all_subject_score.copy()
all_subject_score_after[1][4]= 55
print(
np.nanmean(all_subject_score_after, axis=1),
np.nanmax(all_subject_score_after, axis =1),
np.nanmin(all_subject_score_after, axis =1),
np.nanstd(all_subject_score_after, axis =1),
sep= '\n')

[67.16666667 64.66666667 75.33333333]
[89. 85. 90.]
[48. 55. 65.]
[13.43399502  9.86013297  8.8254682 ]


In [49]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
np.corrcoef(all_subject_score_after)

array([[1.        , 0.7855563 , 0.97792828],
       [0.7855563 , 1.        , 0.74056803],
       [0.97792828, 0.74056803, 1.        ]])